##开发环境配置##

#tomcat
server:
  port: 81
  servlet:
    context-path: /mck
#mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456


